### PR TITLE
Fix build on ubuntu 20.04

### PR DESCRIPTION
**Pull request by dabrain34**
- The bundled glib version does not support G_DEFINE_FINAL_TYPE use of G_DEFINE_TYPE instead
- Ubuntu 20.04 ships with g++ 9.4.0, needs to define c++17 as the minimum version to build with vector and atomic in Picture
```
In file included from /usr/include/c++/9/vector:66,
                 from ../test.cpp:23:
/usr/include/c++/9/bits/stl_uninitialized.h: In instantiation of ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const Picture*, std::vector<Picture> >; _ForwardIterator = Picture*]’:
/usr/include/c++/9/bits/stl_uninitialized.h:307:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const Picture*, std::vector<Picture> >; _ForwardIterator = Picture*; _Tp = Picture]’
/usr/include/c++/9/bits/stl_vector.h:555:31:   required from ‘std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = Picture; _Alloc = std::allocator<Picture>]’
../test.cpp:96:7:   required from here
/usr/include/c++/9/bits/stl_uninitialized.h:127:72: error: static assertion failed: result type must be constructible from value type of input range
  127 |       static_assert(is_constructible<_ValueType2, decltype(*__first)>::value,
```
h265dec: fix build with bad variable names.

### CODE REVIEW

File: h264dec.cpp [hunk 1]
```diff
@@ -85,7 +85,7 @@ enum
   PROP_OOB_PIC_PARAMS,
 };
 
-G_DEFINE_FINAL_TYPE(GstH264Dec, gst_h264_dec, GST_TYPE_H264_DECODER)
```
Comment (ceyusa) [inline h264dec.cpp:88]: is this needed?

File: h265dec.cpp [hunk 2]
```diff
@@ -86,7 +86,7 @@ enum
   PROP_OOB_PIC_PARAMS,
 };
 
-G_DEFINE_FINAL_TYPE(GstH265Dec, gst_h265_dec, GST_TYPE_H265_DECODER)
```
Comment (ceyusa) [inline h265dec.cpp:89]: ditto

File: pipeline.c [hunk 3]
```diff
@@ -41,7 +41,7 @@ enum
 GST_DEBUG_CATEGORY (gst_video_parser_debug);
 #define GST_CAT_DEFAULT gst_video_parser_debug
 
-G_DEFINE_FINAL_TYPE_WITH_CODE (GstVideoParser, gst_video_parser,
```
Comment (ceyusa) [inline pipeline.c:44]: ditto

**Comment by ceyusa** [comment]
Just a couple questions to clarify if final or not mark. The rest looks good.
